const chargers = [
    {
        id: '1',
        name: 'Oulun Energian toimitalon piha',
        location:'Kasarmintie',
        lat:'65.012650',
        lng:'25.471390',
        type:'Type2,22KWh',
        price:'0.22e/min',
        status:'Free',
        code:'A4AA',
    },
    {
        id: '2',
        name: 'K-Citymarket Oulu Kaakkuri',
        location:'Metsokankaantie',
        lat:'64.969360',
        lng:'25.528370',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A7AA',
    },
    {
        id: '3',
        name: 'Lapland Hotels Oulu',
        location:'Kirkkokatu',
        lat:'66.726700',
        lng:'26.969110',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A3AA',
    },
    {
        id: '4',
        name: 'Neste K-Liikenneasema Linnatuuli',
        location:'Helsingintie',
        lat:'60.855221',
        lng:'24.597627',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A1AA',
    },
    {
        id: '5',
        name: 'Kivisydän',
        location:'Hallituskatu',
        lat:'65.012814',
        lng:'25.469660',
        type:'Type2,22KWh',
        price:'0.22e/min',
        status:'Free',
        code:'A5AA',
    },
    {
        id: '6',
        name: 'P-Stockmann',
        location:'Kirkkokatu',
        lat:'65.011870',
        lng:'25.467580',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A6AA',
    },
    {
        id: '7',
        name: 'ABC Särkisalmi',
        location:'Rinnekatu',
        lat:'61.604433',
        lng:'29.482190',
        type:'CCS,50KW',
        price:'18c/KWh',
        status:'Free',
        code:'A2AA',
    },
    {
        id: '8',
        name: 'Kempeleen Ekokortteli',
        location:'Koivikkohaka',
        lat:'64.912080',
        lng:'25.509990',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A8AA',
    },
    {
        id: '9',
        name: 'Pilot Business Park',
        location:'lentokatu',
        lat:'65.012380',
        lng:'25.473110',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A9AA',
    },
    {
        id: '10',
        name: 'Hesburger Pulkkila',
        location:'Jokivarrentie',
        lat:'61.235370',
        lng:'25.492020',
        type:'CCS,50KW',
        price:'18c/KWh',
        status:'Free',
        code:'A10B',
    },
    {
        id: '11',
        name: 'Centrian parkkipaikka',
        location:'Vierimaantie',
        lat:'63.833988',
        lng:'23.158520',
        type:'Type2,22KW',
        price:'0.22e/min',
        status:'Free',
        code:'A11B',
    },
    {
        id: '12',
        name: 'Kärkkäisen parkkialue',
        location:'Ollilanojankatu',
        lat:'64.130419',
        lng:'28.377607',
        type:'Type2,22KW',
        price:'0.22e/min',
        status:'Free',
        code:'A12B',
    },
    {
        id: '13',
        name: 'Kauppakeskus Komppi',
        location:'Karhoistentie',
        lat:'61.130210',
        lng:'21.459950',
        type:'CCS,50KW',
        price:'18c/KWh',
        status:'Free',
        code:'A13B',
    },
    {
        id: '14',
        name: 'Tapion Tupa',
        location:'Matkailutie',
        lat:'64.230460',
        lng:'23.816260',
        type:'CCS,50KW',
        price:'18c/KWh',
        status:'Free',
        code:'A14B',
    },
    {
        id: '15',
        name: 'Anorak',
        location:'Brahenkatu',
        lat:'64.227950',
        lng:'27.731280',
        type:'CCS,50KW',
        price:'18c/KWh',
        status:'Free',
        code:'A15B',
    },
    {
        id: '16',
        name: 'Tahko Spa Hote',
        location:'Keitaankatu',
        lat:'63.291120',
        lng:'28.042020',
        type:'Type2,22KW',
        price:'0.20e/min',
        status:'Free',
        code:'A16B',
    },
    {
        id: '17',
        name: 'Jari-Pekka Hankasalmi',
        location:'Pieksämäentie',
        lat:'62.357860',
        lng:'26.570880',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A17B',
    },
    {
        id: '18',
        name: 'Hämeen Auto',
        location:'Kuormaajantie',
        lat:'62.277409',
        lng:'25.788300',
        type:'Type2,22KW',
        price:'Free',
        status:'Free',
        code:'A18B',
    },
    {
        id: '19',
        name: 'Serlachius-museo',
        location:'Joenniementie',
        lat:'62.027640',
        lng:'24.575380',
        type:'Type2,22KW',
        price:'0.20e/min',
        status:'Free',
        code:'A19B',
    },
    {
        id: '20',
        name: 'Neste Jämsän Portti',
        location:'Kauhkialantie',
        lat:'61.852930',
        lng:'25.173900',
        type:'Type2,22KW',
        price:'0.22e/min',
        status:'Free',
        code:'A20B',
    },
];

export default chargers;